### ISSUE TITLE
This extension is abandoned.

### ISSUE THREAD

**Issue by bauerbach** [snipe/downworthy#85]
Why did snipe abandon the extension without any explanation? Snipe is still around and working on their other stuff, but this extension hasn't been touched in 7 years! The weekly digests stopped and everything!

Anyone know why the extension was abandoned?

**Comment by snipe** [comment]
Because it was a fun idea a decade ago and I have a business to run and people to employ now. Moreover, the trend of hyperbolic headlines sort of faded. They’re still terrible now, but not the same, so it ran its course.
